/**
 * Version Information Module
 * 
 * Provides version, commit hash, and startup time for the server.
 * 
 * Version info sources (in priority order):
 * 1. version.json (generated by scripts/generate-version.js at build time)
 * 2. Environment variables (COMMIT_SHA, BUILD_DATE)
 * 3. Defaults ('dev', current time)
 */

import { readFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Read version from package.json
function getPackageVersion(): string {
  try {
    const packagePath = join(__dirname, '..', 'package.json');
    const packageJson = JSON.parse(readFileSync(packagePath, 'utf-8'));
    return packageJson.version || '0.0.0';
  } catch {
    return '0.0.0';
  }
}

// Read git info from version.json (generated at build time)
interface VersionJson {
  commit?: string;
  commitFull?: string;
  commitDate?: string;
  branch?: string;
  buildDate?: string;
}

function getVersionJson(): VersionJson {
  try {
    // Try multiple paths (dev vs production)
    const paths = [
      join(__dirname, '..', 'version.json'),      // Production: dist/../version.json
      join(__dirname, '..', '..', 'version.json'), // Dev: src/../version.json
    ];
    
    for (const versionPath of paths) {
      if (existsSync(versionPath)) {
        return JSON.parse(readFileSync(versionPath, 'utf-8'));
      }
    }
  } catch {
    // Ignore errors
  }
  return {};
}

const versionJson = getVersionJson();

// Server startup time (captured once at module load)
const startupTime = new Date();

/**
 * Version information object
 */
export const versionInfo = {
  /** Semantic version from package.json */
  version: getPackageVersion(),
  
  /** Git commit SHA (short form, 7 chars) */
  commit: versionJson.commit || (process.env.COMMIT_SHA || 'dev').slice(0, 7),
  
  /** Full Git commit SHA */
  commitFull: versionJson.commitFull || process.env.COMMIT_SHA || 'development',
  
  /** Build date from version.json or CI/CD */
  buildDate: versionJson.buildDate || process.env.BUILD_DATE || null,
  
  /** Git branch (if available) */
  branch: versionJson.branch || null,
  
  /** Server startup timestamp */
  startupTime: startupTime,
  
  /** Human-readable startup time */
  startupTimeFormatted: startupTime.toISOString(),
  
  /** Environment (production/development) */
  environment: process.env.NODE_ENV || 'development',
};

/**
 * Get version string for display
 * Format: "v1.0.0 (abc1234)"
 */
export function getVersionString(): string {
  return `v${versionInfo.version} (${versionInfo.commit})`;
}

/**
 * Get full version info for /version endpoint
 */
export function getVersionDetails(): {
  version: string;
  commit: string;
  commitFull: string;
  buildDate: string | null;
  startupTime: string;
  uptime: string;
  environment: string;
} {
  const now = new Date();
  const uptimeMs = now.getTime() - startupTime.getTime();
  const uptimeHours = Math.floor(uptimeMs / (1000 * 60 * 60));
  const uptimeMinutes = Math.floor((uptimeMs % (1000 * 60 * 60)) / (1000 * 60));
  
  return {
    version: versionInfo.version,
    commit: versionInfo.commit,
    commitFull: versionInfo.commitFull,
    buildDate: versionInfo.buildDate,
    startupTime: versionInfo.startupTimeFormatted,
    uptime: `${uptimeHours}h ${uptimeMinutes}m`,
    environment: versionInfo.environment,
  };
}

/**
 * HTML footer snippet with version info
 */
export function getVersionFooterHtml(): string {
  const details = getVersionDetails();
  return `
    <div class="version-info">
      <span class="version">v${details.version}</span>
      <span class="commit">${details.commit}</span>
      <span class="startup" title="Server started: ${details.startupTime}">Up: ${details.uptime}</span>
    </div>
  `;
}

/**
 * CSS for version footer
 */
export const versionFooterCss = `
  .version-info {
    display: flex;
    gap: 1rem;
    align-items: center;
    font-size: 0.75rem;
    color: #6b7280;
    font-family: 'SF Mono', Monaco, 'Cascadia Code', monospace;
  }
  .version-info .version {
    color: #10b981;
  }
  .version-info .commit {
    color: #8b5cf6;
  }
  .version-info .startup {
    color: #6b7280;
    cursor: help;
  }
`;
